### ISSUE TITLE
关于网络对四条边距离的输出

### ISSUE THREAD

**Issue by Banyueqin** [SakuraRiven/EAST#10]
您好，谢谢您的工作。
我想问一下关于网络输出的部分：
loc   = self.sigmoid2(self.conv2(x)) * self.scope
1.这里self.scope的值是输入图片的尺寸512，对吗？
2.self.scope如果是输入图片的尺寸，那么self.sigmoid2(self.conv2(x))的值应该很小对吗，比如都是0-0.1之间的值，有可能更小，这对训练回归影响大吗？

期待您的回复，谢谢！

**Comment by SakuraRiven** [comment]
如果可以预先得知数据的具体分布的话，可以适当地缩小，但问题是实际应用中这个信息不好得到……
而且sigmoid之前是conv层，再加上有bn的存在，所以影响也不是很大的

**Comment by Banyueqin** [comment]
谢谢回复
