### ISSUE TITLE
cannot re-implement your work

### ISSUE THREAD

**Issue by CuriousCat-7** [SakuraRiven/EAST#11]
I train the network from vgg16_bn-6c64b313.pth and eval it, 
got 
Calculated!{"precision": 0.7974987974987975, "recall": 0.79826673086182, "hmean": 0.7978825794032723, "AP": 0}
in save/model_epoch_600.pth

BTW, I eval the east_vgg16.pth get your original score:
Calculated!{"precision": 0.8435782108945528, "recall": 0.8127106403466539, "hmean": 0.8278567925453654, "AP": 0}
So, I used the right code and model.

What's wrong in there?
Should I use earlier epoch?

Yours,
Neo

**Comment by SakuraRiven** [comment]
Actually, I tested models with all epochs and pick the best on ICDAR2015... OTZ

**Comment by CuriousCat-7** [comment]
> Actually, I tested models with all epochs and pick the best on ICDAR2015... OTZ

Got it, thank you.
