### ISSUE TITLE
Loss differences wrt paper

### ISSUE THREAD

**Issue by lukszamarcin** [SakuraRiven/EAST#18]
I'm not sure whether it's a bug or just difference in variable naming
In loss.py, you define the width and height of the union box as:
```
w_union = torch.min(d3_gt, d3_pred) + torch.min(d4_gt, d4_pred)
h_union = torch.min(d1_gt, d1_pred) + torch.min(d2_gt, d2_pred)
```
while in original paper it is:
wi= min(d2_gt,d2_pred) + min(d4_gt,d4_pred)
hi= min(d1_gt,d1_pred) + min(d3_gt,d3_pred)

Could you please clarify?

**Comment by SakuraRiven** [comment]
The variable naming does not matter as long as the decode function `restore_polys` (in detect.py) is align with encode order.

**Comment by lukszamarcin** [comment]
I see now, thanks for the clarification!
