### ISSUE TITLE
What may cause " Points are not clockwise. "

### ISSUE THREAD

**Issue by ranye92** [SakuraRiven/EAST#39]
I changed the Loss a little bit then train for 200 epochs and I met " Points are not clockwise"  at evaluation. But when I tried to do the same thing on the original EAST model this phenomenon didn't happen. I wonder what may cause " Points are not clockwise. " Is it just means my result is bad or something else ?

**Comment by SuitsHe** [comment]
I met the same error. "Points are not clockwise". Could you please tell me how do you solve that?
