### ISSUE TITLE
time for training

### ISSUE THREAD

**Issue by mengliu1998** [SakuraRiven/EAST#4]
Thanks for your open source!!!
I am curious about how much time it cost to train the model until converge.
~~

**Comment by SakuraRiven** [comment]
I set 900 epochs for training and the lr is 1e-3, 1e-4, 1e-5 in [0-300], [300-600], [600-900] epoch. Generally, the best model are around 400 epochs, which can obtain about 82 F-score. So in the new version, I delete the last stage (600-900 epoch) and only keep the [0-600] epochs. Actually, the training may be shortened furthermore.

In my environment (2 gpus used and num_workers is 4), each epoch cost 40-50s

**Comment by mengliu1998** [comment]
@SakuraRiven Thank you.

**Comment by gathierry** [comment]
@SakuraRiven Hi, I trained on 2GPUs with num_workers=4 and it was very slow? Are you sure it is "one epoch" that takes 40-50s instead of "one batch"?
How long does it take for whole 600 epochs then?
