### ISSUE TITLE
ZIP entry not valid

### ISSUE THREAD

**Issue by vulyon** [SakuraRiven/EAST#51]
(mmdetection) wuliang@gpu5:~/cvprojects/EAST-master$ python ./evaluate/script.py –g=./evaluate/gt.zip –s=./submit.zip
Error!
ZIP entry not valid: 595.txt

我想用我的数据集评估我的模型。不知道为什么不行

**Comment by wangjiaxuan10** [comment]
您好，请问怎么解决的
