### ISSUE TITLE
can not repeat your result

### ISSUE THREAD

**Issue by phucnsp** [SakuraRiven/EAST#6]
Hi SakuraRiven,
I have cloned your repository and try to run eval.py file, it outputs precision 0.014, recall 0.8574 and hmean 0.028. It is so strange to me, do you have any comment?

**Comment by SakuraRiven** [comment]
Hi, have you solved the problem?

**Comment by phucnsp** [comment]
yes, my mistake. 
btw, I am trying to convert your source code to adapt with fastai library. By using fastai library and its transformation sets, the convertsion is much slower.
