### ISSUE TITLE
install lanms

### ISSUE THREAD

**Issue by phucnsp** [SakuraRiven/EAST#7]
Hi,
Do you know how to install lanms in MacOS?

**Comment by SakuraRiven** [comment]
I only tested on linux. If you cannot install lanms, the python file in https://github.com/songdejia/EAST may help

**Comment by www516717402** [comment]
@phucnsp you can write a lanms by Python or make a lanms by C. Install lanms directly in MaxOS may mistake.

**Comment by ZhangXinNan** [comment]
How can i use it in Windows 10 ?

**Comment by samtlink** [comment]
@ZhangXinNan Have you found a solution? I am having an error while installing lanms on windows.
The error is as follows:
/dll
/implib:adaptor.lib
/out:adaptor.pyd
/LIBPATH:C:\ProgramData\Anaconda3\libs
adaptor.obj
clipper.obj
**python37.lib(python37.dll) : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'**
